name: Bug Report
description: Create a report to help us improve facileManager and its modules
title: "[BUG] "
labels: ["bug-report"]
type: "Bug"
projects: ["facileManager"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug for facileManager and its modules.

        All submitters MUST read the [issue policy and reporting guidelines](https://docs.facilemanager.com/issues/). Bug reports that do not follow the issue policy will be marked as `invalid` and closed. Likewise, bug reports missing required fields will be marked `incomplete` and closed (no hard feelings).
        In this event, we ask you to re-submit a complete bug report.
        
        Be sure there are no issues similar to yours that are already open. You can check this by searching the issues in this repository.
        If there is a duplicate issue, please comment on the existing issue instead.

  - type: checkboxes
    id: policies
    attributes:
      label: Issue reporting checklist
      options:
        - label: I have read and understood the [contributors guide](https://github.com/facileManager/facileManager/blob/master/.github/CONTRIBUTING.md).
          required: true
        - label: I have followed the [project prerequisites](https://docs.facilemanager.com/getting-started/prerequisites/).
          required: true
        - label: I have searched this repository for [existing issues](https://github.com/facileManager/facileManager/issues) and [pull requests](https://github.com/facileManager/facileManager/pull) related to my issue/suggestion.
          required: true
        - label: I checked the [FAQs](https://docs.facilemanager.com/faq/) and [official documentation](https://docs.facilemanager.com/).
          required: true

  - type: input
    id: fm-version
    attributes:
      label: facileManager Version
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Module
      options:
        - fmDHCP
        - fmDNS
        - fmFirewall
        - fmSQLPass	
        - fmWifi
        - None (fM Core only)
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: Module Version
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Also tell us, what did you expect to happen?
      placeholder: Provide a clear and concise description of the issue.
      value:
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce this issue.
      placeholder: |
        Provide as much detailed information as possible.
        
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value:
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Upload your screenshot(s) here.
      value:
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: 
      placeholder: Add any other context about the problem here.
      value:
    validations:
      required: false
